import pandas as pd
from matplotlib import pyplot as plt

country_translation = {
    "AFG": "Afghanistan",
    "AHO": "Netherlands Antilles",
    "AIN": "Ashmore and Cartier Islands",
    "ALB": "Albania",
    "ALG": "Algeria",
    "AND": "Andorra",
    "ANG": "Angola",
    "ANT": "Antigua and Barbuda",
    "ANZ": "Australasia",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ARU": "Aruba",
    "ASA": "American Samoa",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BAH": "Bahamas",
    "BAN": "Bangladesh",
    "BAR": "Barbados",
    "BDI": "Burundi",
    "BEL": "Belgium",
    "BEN": "Benin",
    "BER": "Bermuda",
    "BHU": "Bhutan",
    "BIH": "Bosnia and Herzegovina",
    "BIZ": "Belize",
    "BLR": "Belarus",
    "BOH": "Bohemia",
    "BOL": "Bolivia",
    "BOT": "Botswana",
    "BRA": "Brazil",
    "BRN": "Bahrain",
    "BRU": "Brunei",
    "BUL": "Bulgaria",
    "BUR": "Burkina Faso",
    "CAF": "Central African Republic",
    "CAM": "Cambodia",
    "CAN": "Canada",
    "CAY": "Cayman Islands",
    "CGO": "Congo",
    "CHA": "Chad",
    "CHI": "Chile",
    "CHN": "China",
    "CIV": "Côte d'Ivoire",
    "CMR": "Cameroon",
    "COD": "Democratic Republic of the Congo",
    "COK": "Cook Islands",
    "COL": "Colombia",
    "COM": "Comoros",
    "CPV": "Cabo Verde",
    "CRC": "Costa Rica",
    "CRO": "Croatia",
    "CRT": "Caribbean Team",
    "CUB": "Cuba",
    "CYP": "Cyprus",
    "CZE": "Czech Republic",
    "DEN": "Denmark",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "EOR": "Refugee Olympic Team",
    "ERI": "Eritrea",
    "ESA": "El Salvador",
    "ESP": "Spain",
    "EST": "Estonia",
    "ETH": "Ethiopia",
    "EUN": "Unified Team",
    "FIJ": "Fiji",
    "FIN": "Finland",
    "FRA": "France",
    "FRG": "West Germany",
    "FSM": "Federated States of Micronesia",
    "GAB": "Gabon",
    "GAM": "Gambia",
    "GBR": "Great Britain",
    "GBS": "Guinea-Bissau",
    "GDR": "East Germany",
    "GEO": "Georgia",
    "GEQ": "Equatorial Guinea",
    "GER": "Germany",
    "GHA": "Ghana",
    "GRE": "Greece",
    "GRN": "Grenada",
    "GUA": "Guatemala",
    "GUI": "Guinea",
    "GUM": "Guam",
    "GUY": "Guyana",
    "HAI": "Haiti",
    "HKG": "Hong Kong",
    "HON": "Honduras",
    "HUN": "Hungary",
    "INA": "Indonesia",
    "IND": "India",
    "IOA": "Independent Olympic Athletes",
    "IRI": "Iran",
    "IRL": "Ireland",
    "IRQ": "Iraq",
    "ISL": "Iceland",
    "ISR": "Israel",
    "ISV": "Virgin Islands (U.S.)",
    "ITA": "Italy",
    "IVB": "British Virgin Islands",
    "JAM": "Jamaica",
    "JOR": "Jordan",
    "JPN": "Japan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KGZ": "Kyrgyzstan",
    "KIR": "Kiribati",
    "KOR": "South Korea",
    "KOS": "Kosovo",
    "KSA": "Saudi Arabia",
    "KUW": "Kuwait",
    "LAO": "Laos",
    "LAT": "Latvia",
    "LBA": "Libya",
    "LBN": "Lebanon",
    "LBR": "Liberia",
    "LCA": "Saint Lucia",
    "LES": "Lesotho",
    "LIB": "Lebanon",
    "LIE": "Liechtenstein",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "MAD": "Madagascar",
    "MAL": "Malaysia",
    "MAR": "Morocco",
    "MAS": "Malaysia",
    "MAW": "Malawi",
    "MDA": "Moldova",
    "MDV": "Maldives",
    "MEX": "Mexico",
    "MGL": "Mongolia",
    "MHL": "Marshall Islands",
    "MKD": "North Macedonia",
    "MLI": "Mali",
    "MLT": "Malta",
    "MNE": "Montenegro",
    "MON": "Monaco",
    "MOZ": "Mozambique",
    "MRI": "Mauritius",
    "MTN": "Mauritania",
    "MYA": "Myanmar",
    "NAM": "Namibia",
    "NBO": "North Borneo",
    "NCA": "Nicaragua",
    "NED": "Netherlands",
    "NEP": "Nepal",
    "NFL": "Newfoundland",
    "NGR": "Nigeria",
    "NIG": "Niger",
    "NOR": "Norway",
    "NRU": "Nauru",
    "NZL": "New Zealand",
    "OMA": "Oman",
    "PAK": "Pakistan",
    "PAN": "Panama",
    "PAR": "Paraguay",
    "PER": "Peru",
    "PHI": "Philippines",
    "PLE": "Palestine",
    "PLW": "Palau",
    "PNG": "Papua New Guinea",
    "POL": "Poland",
    "POR": "Portugal",
    "PRK": "North Korea",
    "PUR": "Puerto Rico",
    "QAT": "Qatar",
    "RHO": "Rhodesia",
    "ROC": "Russian Olympic Committee",
    "ROT": "Refugee Olympic Team",
    "ROU": "Romania",
    "RSA": "South Africa",
    "RUS": "Russia",
    "RWA": "Rwanda",
    "SAA": "Saar",
    "SAM": "Samoa",
    "SCG": "Serbia and Montenegro",
    "SEN": "Senegal",
    "SEY": "Seychelles",
    "SGP": "Singapore",
    "SKN": "Saint Kitts and Nevis",
    "SLE": "Sierra Leone",
    "SLO": "Slovenia",
    "SMR": "San Marino",
    "SOL": "Solomon Islands",
    "SOM": "Somalia",
    "SRB": "Serbia",
    "SRI": "Sri Lanka",
    "SSD": "South Sudan",
    "STP": "São Tomé and Príncipe",
    "SUD": "Sudan",
    "SUI": "Switzerland",
    "SUR": "Suriname",
    "SVK": "Slovakia",
    "SWE": "Sweden",
    "SWZ": "Eswatini",
    "SYR": "Syria",
    "TAN": "Tanzania",
    "TCH": "Czechoslovakia",
    "TGA": "Tonga",
    "THA": "Thailand",
    "TJK": "Tajikistan",
    "TKM": "Turkmenistan",
    "TLS": "Timor-Leste",
    "TOG": "Togo",
    "TPE": "Chinese Taipei",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TUV": "Tuvalu",
    "UAE": "United Arab Emirates",
    "UAR": "United Arab Republic",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "UNK": "Unknown",
    "URS": "Soviet Union",
    "URU": "Uruguay",
    "USA": "United States",
    "UZB": "Uzbekistan",
    "VAN": "Vanuatu",
    "VEN": "Venezuela",
    "VIE": "Vietnam",
    "VIN": "Saint Vincent and the Grenadines",
    "VNM": "Vietnam",
    "WIF": "West Indies Federation",
    "YAR": "Yemen Arab Republic",
    "YEM": "Yemen",
    "YMD": "South Yemen",
    "YUG": "Yugoslavia",
    "ZAM": "Zambia",
    "ZIM": "Zimbabwe"
}

# Load the dataset
athletes_count_by_country = pd.read_csv('data/athletes_count_by_country.csv')
medal_counts = pd.read_csv('data/summerOly_medal_counts.csv')

year_index = athletes_count_by_country['Year']

country_record = {}

for col in athletes_count_by_country.columns:
    if col == 'Year':
        continue
    year_record = {}
    country_records = medal_counts[medal_counts['NOC'] == country_translation[col]]
    for row in country_records.iterrows():
        year = row[1]['Year']
        count = row[1]['Total']
        year_record[year] = count
    country_record[col] = year_record
    # plot the trend
    plt.plot(year_record.keys(), year_record.values(), label=col)
    plt.plot(year_index, athletes_count_by_country[col], label=col + ' Athletes')
    plt.legend()
    plt.show()
